name: bulma_min
description: Bulma is a CSS Framework. This package contains its minified assets to include in your project.
version: 0.9.3
homepage: https://github.com/agilord/bulma_min

environment:
  sdk: '>=2.12.0 <3.0.0'
